<?php
/**
 * @file
 * Gallery tiler main code.
 */

/**
 * Implements hook_field_formatter_info().
 */
function gallery_tiler_field_formatter_info() {
  $formats = array(
    'tiled_gallery' => array(
      'label' => t('Tiled gallery'),
      'field types' => array(
        'image',
      ),
      'settings' => array(
        'type' => 'compact',
        'image_style' => NULL,
        'breakpoint' => 960,
        'tile_height' => 220,
        'gutter' => 0,
        'colorbox' => FALSE,
        'colorbox_image_style' => NULL,
      ),
    ),
  );
  return $formats;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function gallery_tiler_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();

  $element['type'] = array(
    '#type' => 'select',
    '#title' => t('Gallery type'),
    '#options' => _gallery_tiler_type_options(),
    '#default_value' => $settings['type'],
    '#required' => TRUE,
  );
  $image_styles = image_style_options(FALSE, PASS_THROUGH);
  $element['image_style'] = array(
    '#type' => 'select',
    '#title' => t('Image style'),
    '#default_value' => $settings['image_style'],
    '#empty_option' => t('None (original image)'),
    '#options' => $image_styles,
  );
  $element['breakpoint'] = array(
    '#type' => 'number',
    '#title' => t('Breakpoint'),
    '#min' => 450,
    '#max' => 1500,
    '#default_value' => $settings['breakpoint'],
    '#field_suffix' => 'px',
  );
  $element['tile_height'] = array(
    '#type' => 'number',
    '#title' => t('Tile height'),// @todo wording.
    '#min' => 90,
    '#max' => 300,
    '#default_value' => $settings['tile_height'],
    '#field_suffix' => 'px',
  );
  $element['gutter'] = array(
    '#type' => 'number',
    '#title' => t('Gutter (gap between tiles)'),
    '#min' => 0,
    '#max' => 25,
    '#default_value' => $settings['gutter'],
    '#field_suffix' => 'px',
  );
  $element['colorbox'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use colorbox'),
    '#default_value' => module_exists('colorbox') ? $settings['colorbox'] : FALSE,
    '#disabled' => !module_exists('colorbox'),
  );
  $element['colorbox_image_style'] = array(
    '#type' => 'select',
    '#title' => t('Colorbox image style'),
    '#default_value' => module_exists('colorbox') ? $settings['colorbox_image_style'] : NULL,
    '#empty_option' => t('None (original image)'),
    '#options' => $image_styles,
  );

  return $element;
}

/**
 * Helper function to return an option list.
 */
function _gallery_tiler_type_options() {
  return array(
    'compact' => t('Compact'),
    'pitted' => t('Pitted'),
    'mountain' => t('Mountain'),
    'french' => t('French'),
  );
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function gallery_tiler_field_formatter_settings_summary($field, $instance, $view_mode) {
  $settings = $instance['display'][$view_mode]['settings'];
  $types = _gallery_tiler_type_options();
  $variables = array('type' => 'ul');
  foreach ($settings as $key => $value) {
    switch ($key) {
      case 'type':
        $variables['items'][] = t('Type') . ': <strong>' . $types[$value] . '</strong>';
        break;

      case 'image_style':
        $variables['items'][] = t('Image style') . ': ' . $value;
        break;

      case 'breakpoint':
        $variables['items'][] = t('Breakpoint') . ': ' . $value . 'px';
        break;

      case 'gutter':
        $variables['items'][] = t('Gutter') . ': ' . $value . 'px';
        break;

      case 'colorbox':
        if ($value) {
          $variables['items'][] = t('Use colorbox: yes');
        }
        break;

      case 'colorbox_image_style':
        if ($settings['colorbox']) {
          $variables['items'][] = t('Colorbox image style') . ': ' . $value;
        }
        break;

    }
  }
  return theme('item_list', $variables);
}

/**
 * Implements hook_field_formatter_view().
 */
function gallery_tiler_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  if ($display['type'] == 'tiled_gallery') {
    // @todo consider css file per type?
    $path = backdrop_get_path('module', 'gallery_tiler');
    $breakpoint = $display['settings']['breakpoint'];
    $element['#attached']['css'] = array(
      $path . '/css/gallery-tiler.css',
      $path . '/css/gallery-tiler-media.css' => array(
        'media' => "(min-width: {$breakpoint}px)",
      ),
    );

    $use_colorbox = FALSE;
    $cbox_image_style = FALSE;
    if (module_exists('colorbox') && $display['settings']['colorbox']) {
      // @todo Settings... is there an easier way?
      $element['#attached']['library'][] = array('colorbox', 'colorbox');
      $element['#attached']['js'][] = $path . '/js/gallery-tiler.js';
      $use_colorbox = TRUE;
      if (isset($display['settings']['colorbox_image_style'])) {
        $cbox_image_style = $display['settings']['colorbox_image_style'];
      }
    }

    foreach ($items as $delta => $item) {
      if ($use_colorbox) {
        if ($cbox_image_style) {
          $file_url = image_style_url($cbox_image_style, $item['uri']);
        }
        else {
          $file_url = file_create_url($item['uri']);
        }
        $uri = array(
          'path' => $file_url,
          'options' => array('attributes' => array('rel' => 'gallery')),
        );
      }
      $element[$delta] = array(
        '#theme' => 'image_formatter',
        '#item' => $item,
        '#image_style' => $display['settings']['image_style'],
        '#path' => isset($uri) ? $uri : '',
      );
    }
  }
  return $element;
}

/**
 * Implements hook_preprocess_field().
 */
function gallery_tiler_preprocess_field(&$variables) {
  if ($variables['element']['#formatter'] == 'tiled_gallery') {
    // Custom template file.
    $variables['theme_hook_suggestions'] = array('gallery_tiler_field');

    $element = $variables['element'];
    $entity_type = !empty($element['#entity_type']) ? $element['#entity_type'] : '';
    $field_name = !empty($element['#field_name']) ? $element['#field_name'] : '';
    $bundle = !empty($element['#bundle']) ? $element['#bundle'] : '';
    $view_mode = !empty($element['#view_mode']) ? $element['#view_mode'] : '';

    $formatter_info = field_formatter_settings_get_instance_display_settings($entity_type, $field_name, $bundle, $view_mode);
    $variables['classes'][] = 'gallery-tiler';
    $variables['classes'][] = 'gallery-tiler-' . $formatter_info['type'];
    // Set CSS variables. @todo make this easer to read.
    $variables['content_attributes']['style'] = '--height: ' . $formatter_info['tile_height'] . 'px; --gap: ' . $formatter_info['gutter'] . 'px;';
  }
}

/**
 * Implements hook_theme().
 */
function gallery_tiler_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['gallery_tiler_field'] = array(
    'template' => 'field-gallery-tiler',
    'path' => drupal_get_path('module', 'gallery_tiler') . '/templates',
  );
  return $theme;
}
